# Generated by Django 2.1.5 on 2019-07-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180417_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, default=0, upload_to='restaurant_logos'),
            preserve_default=False,
        ),
    ]
